org: nirdeshkumar
app: aws-python-project
service: aws-python-project

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: results
          method: get
      - http:
          path: query
          method: post
        
